# Generated by Django 4.0.2 on 2022-02-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
